name: Build and Deploy Locally

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-and-deploy-locally:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache npm dependencies
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.12.0"

      - name: Install npm dependencies
        run: npm install

      - name: Build Theme
        run: npm run build
        working-directory: themes/web-digitalschool

      - name: Deploy Locally
        run: |
          # Replace this with your actual deployment command
          rsync -av --exclude=node_modules/ themes/web-digitalschool/ /var/www/shkolla/wp-content/themes/web-digitalschool
          
      - name: Set Permissions Locally
        run: |
          # Replace this with your actual permission-setting command
          sudo chown -R www-data:www-data /var/www/shkolla/wp-content/themes/web-digitalschool
